plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'com.ferra13671'
version = '1.7'

java {
    withSourcesJar()
}

repositories {
    mavenCentral()
}

dependencies {
    compileOnly("org.projectlombok:lombok:1.18.42")
    annotationProcessor("org.projectlombok:lombok:1.18.42")
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = 'com.ferra13671'
            artifactId = 'mega-events'
            artifact source: jar, classifier: null
            artifact sourcesJar
        }
    }

    repositories {
        mavenLocal()
    }
}